### ISSUE TITLE
Graphite output not supported

### ISSUE THREAD

**Issue by nezlis** [sensu/sensu-prometheus-collector#21]
Hey there, have a difficult times to run this collector with graphite output.

As READ.me suggests to use "{influx|graphite|json}" i have simple definition for sensu assets like so:

```
---
type: CheckConfig
api_version: core/v2
metadata:
name: sensu-prom-metrics
spec:
  command: sensu-prometheus-collector -exporter-url http://127.0.0.1:9100/metrics
  output_metric_format: graphite
  output_metric_handlers:
  - graphite
  runtime_assets:
  - sensu/sensu-prometheus-collector
  interval: 10
  subscriptions:
  - metrics
  timeout: 5
  ttl: 0
```

but got errors while trying to create asset using sensuctl create -f <filename> like so:

> Error: error putting resource #0 with name "sensu-prom-metrics" and namespace "default (/api/core/v2/namespaces/default/checks/sensu-prom-metrics): resource is invalid: output metric format is not valid

So the question is - what we need to set into "output_metric_format" string to get graphite output?

Thanks!!!
